server:
  port: 8804
mybatis-plus:
  type-aliases-package: com.springcloud.api
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-record
  cloud:
    nacos:
      discovery:
        server-addr: 47.120.3.92:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.120.3.92:3306/springbootwms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

info:
  app.name: cchSpringcloud
  company.name: test
