server:
  port: 80
#eureka:
#  client:
#    register-with-eureka: false #不注册自己
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.120.3.92:8848
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springbootwms?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 1234